src/AspNetCoreSpa.STS/Controllers/SetLanguageController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreSpa.STS.Controllers
{
    public class SetLanguageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl, string returnUrlForLanguageSwitch)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return Redirect(returnUrlForLanguageSwitch);
        }
    }
}

src/AspNetCoreSpa.STS/Views/Shared/_Layout.cshtml
@using AspNetCoreSpa.STS.Resources
@inject LocService SharedLocalizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Identity server</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico?v1" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico?v1" />
    <link rel="stylesheet" href="~/css/vendor.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">
            <img src="~/icon.jpg" width="30" height="30" class="d-inline-block align-top" alt="Logo">
                <em>Identity server</em>
            </a>
            <button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#topNavbarCollapse" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="topNavbarCollapse">
                <ul class="mr-auto navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">@SharedLocalizer.GetLocalizedHtmlString("HOME")</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>

    </header>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="footer">
        <hr />
        <div class="container">
            
            &copy; 2018 - Identity server

            <div class="float-right">
                        @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </div>
    </footer>
    <script src="~/js/vendor.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

src/AspNetCoreSpa.STS/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@using AspNetCoreSpa.STS.Resources
@inject LocService SharedLocalizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    @{ 
        var location = new Uri($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}");

        var url = location.AbsoluteUri;
        var returnUrlForLanguageSwitch = Context.Request.Path;

        if (Context.Request.QueryString.HasValue)
        {
            returnUrlForLanguageSwitch = $"{Context.Request.Path}{Context.Request.QueryString.Value}";
        }
    }

    <form class="form-inline" id="selectLanguage" asp-controller="SetLanguage" asp-action="SetLanguage" asp-route-returnUrl="@returnUrlForLanguageSwitch" method="post" role="form">
        <label class="form-label paddingright5px" >@SharedLocalizer.GetLocalizedHtmlString("LANGUAGE"):&nbsp;</label>
        <div class="input-group">
            <select class="custom-select" name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
            <input type="hidden" name="returnUrlForLanguageSwitch" id="returnUrlForLanguageSwitch" value="@url"/>
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary">@SharedLocalizer.GetLocalizedHtmlString("SAVE")</button>
            </div>
        </div>
    </form>
    
</div>

src/AspNetCoreSpa.STS/Views/Shared/_ValidationSummary.cshtml
@using AspNetCoreSpa.STS.Resources
@inject LocService SharedLocalizer
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}